sudo: false
language: node_js
node_js:
- '5.9'
script:
- npm run lint
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: robert.rossmann@strv.com
  api_key:
    secure: mKhdYMAExMjX1RbjEi3gtpAYr194scDC/xnkIs2FniucIuBPRNz51vPm0yJ52yqmrfhQxZNc44y9ObXTJ18aQHTWicTpAImL+E7Ns0qV5zjIL/ai9GxCQ6+v69oXHTM/wZdHPF4/8oDOM3hKPo+6N8CIUaiPvcAeq9iMY/AMGr7OwRRNKtUB+QZ6DHBTdIlS68vJxsymebh0DFhVMEBXEzVr+fiP8i5BRnm24HDsn7X7DF2WqEm3Cj60dGqIIsGF687ma90kufi6Ph1lSBZvGigJyq5PFid70qHu1vPuWMosqGJO74xrqzGcvAIge3CUro8l+hHXI7sBv4PkPmQ7Ug+8RNFuYo1t1uHmLB7CDU5JC8vVIgdkKfIwDLggIV5FVnDNrpmBkxUDWLQ+TKxppWYF94NdIHaKkTEFvRvSVwdKOWxk8gAiexurEznxs41es5Ckn7r8tZr8uTNZeVD70khfwM6/K+5r1dN+ZPU6kDE+JBucg5kZRxufRRBzbRera6+SKoi7hk1kuaz8MtzK9cXoIZskU2kh5kyO9mP8ui+kNvLtnMAlD7n32ennIw8p7YlR6D6qV+Nly0ajcaTZpSQB32Nr/N/qyiqNhr1HHeewYNiBEowbxfBywbXYzD7ZsxXIjKlAn8lyiQ9GwSd3P/uw4XMqU8MFwv/UKttMHDs=
  on:
    tags: true
    repo: strvcom/js-coding-standards
